name: build python package and upload to pypi

on:
  push:
    branches: [ 'main' ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


  build:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v2
      - name: get version
        id: get_version
        run: |
          echo "import ${{ github.event.repository.name }}\nprint(${{ github.event.repository.name }}.__version__" >> get_version.py
          echo ::set-output name=VERSION::$(python get_version.py)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          pip install -r requirements.txt
          pip install build
      - name: build package
        run: |
          python setup.py sdist bdist_wheel
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          automatic_release_tag: v${{ steps.get_version.outputs.VERSION }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: v${{ steps.get_version.outputs.VERSION }}
          files: dist/*
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

