name: build python package and upload to pypi

on:
  push:
    branches: [ 'main' ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install standard python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: test with pytest
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v2
      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::python -c "import ${{ github.event.repository.name }}; print(${{ github.event.repository.name }}.__version__)"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          pip install build
      - name: build package
        run: |
          python setup.py sdist bdist_wheel
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: v${{ steps.get_version.outputs.VERSION }}
          files: dist/*
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

